



<ol id="plist" class="clearfix">
	<li><a href="index.html">トップページ</a></li>
	<li><a href="../index">企業規模一覧</a></li>
	<li><span>企業規模詳細</span></li>
</ol>

<?php
	foreach($data as $branch){
?>
<table class="tbl_type01 mb1e w100">
	<tr>
		<th class="w25">企業規模コード</th>
		<td class="w75"><?php echo $branch['com_grd_cd']; ?></td>
	</tr>
	<tr>
		<th>企業規模名</th>
		<td><?php echo $branch['com_grd_name']; ?></td>
	</tr>
</table>

<div class="ta_c"><button onclick="location.href='../index'">戻る</button>　<button onclick="location.href='../edit/<?php echo $branch['id']; ?>'">編集</button></div>

<?php
	}
?>


















