

<ol id="plist" class="clearfix">
	<li><a href="index.html">トップページ</a></li>
	<li><span>企業規模一覧</span></li>
</ol>

<table class="tbl_type03 w100">
	<tr>
		<th class="w15">企業規模コード</th>
		<th class="w75">企業規模名</th>
		<th class="w10"></th>
	</tr>
	<?php
		foreach ($data as $record) {
	?>
	<tr>
		<td>
			<a href="detail/<?php echo $record['id'] ; ?>">
				<?php echo $record['com_grd_cd']; ?>
			</a>
		</td>
		<td>
			<a href="detail/<?php echo $record['id'] ; ?>">
				<?php echo $record['com_grd_name']; ?>
			</a>
		</td>
		<td class="ta_c"><button onclick="event.preventDefault();location.href='delete/<?php echo $record['id']; ?>'">削除</button></td>
	<?php
		}
	?>
</table>












