

<?php
	foreach($data as $branch){
?>

<ol id="plist" class="clearfix">
	<li><a href="index.html">トップページ</a></li>
	<li><a href="../index">営業所一覧</a></li>
	<li><a href="../detail/<?php echo $branch['id']; ?>">営業所詳細</a></li>
	<li><span>営業所詳細編集</span></li>
</ol>

<form action="../update/<?php echo $branch['id']; ?>" method="POST">
	<table class="tbl_type01 mb1e w100">
		<tr>
			<th class="w25">営業所コード</th>
			<td class="w75"><input name="branch_cd" class="w60" type="text" value="<?php echo $branch['branch_cd']; ?>"></td>
		</tr>
		<tr>
			<th>営業所名</th>
			<td><input class="w60" name="branch_name" type="text" value="<?php echo $branch['branch_name']; ?>"></td>
		</tr>
		<tr>
			<th>郵便番号</th>
			<td><input class="w60" name="branch_postcode" type="text" value="<?php echo $branch['branch_postcode']; ?>"></td>
		</tr>
		<tr>
			<th>住所１</th>
			<td><input class="w60" name="branch_add1" type="text" value="<?php echo $branch['branch_add1']; ?>"></td>
		</tr>
		<tr>
			<th>住所２</th>
			<td><input class="w60" name="branch_add2" type="text" value="<?php echo $branch['branch_add2']; ?>"></td>
		</tr>
		<tr>
			<th>電話番号</th>
			<td><input class="w60" name="branch_tel" type="text" value="<?php echo $branch['branch_tel']; ?>"></td>
		</tr>
		<tr>
			<th>FAX番号</th>
			<td><input class="w60" name="branch_fax" type="text" value="<?php echo $branch['branch_fax']; ?>"></td>
		</tr>
	</table>

	<div class="ta_c">
		<button onclick="event.preventDefault();location.href='../detail/<?php echo $branch['id']; ?>'">戻る</button>
		<button onclick="event.preventDefault();this.form.submit()'">編集</button>
	</div>
</form>
<?php
	}
?>






