
<ol id="plist" class="clearfix">
	<li><a href="index.html">トップページ</a></li>
	<li><span>部門一覧</span></li>
</ol>

<table class="tbl_type03 w100">
	<tr>
		<th class="w20">部門コード</th>
		<th>部門名</th>
	</tr>
	<?php
		foreach ($data as $record) {
	?>
	<tr>
		<td>
			<a href="detail?id=<?php echo $record['id'] ; ?>">
				<?php echo $record['post_cd']; ?>
			</a>
		</td>
		<td>
			<a href="detail?id=<?php echo $record['id'] ; ?>">
				<?php echo $record['post_name']; ?>
			</a>
		</td>
	<?php
		}
	?>
</table>