<?php echo $this->doctype(); ?>
<html lang="ja" class="no-js">
<head>
</head>


<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<?php echo $this->headTitle('C '. $this->translate('Side'))->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable = no"')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
					->prependStylesheet($this->basePath('css/default.css'))	?>

	<!-- Scripts -->

</head>


<body>

<!-- header start -->
<header>
	<div id="header">
		<ul id="user">
			<li>2015年7月7日</li>
			<li>支局名</li>
			<li>社員ID</li>
			<li>社員名</li>
		</ul>
		<div id="logout"><a href="login2.html"></a></div>
	</div>
</header>
<!-- //header end -->


<!-- main start -->
<div id="main">
	<!-- slidemenu start -->
	<div class="slidemenu slidemenu-left">
		<nav class="slidemenu-body">
			<ul class="slidemenu-content">
				<li><a class="menu-item" href="http://localhost/zf2/public">トップページ</a></li>
				<li><a class="menu-item" href="fm_sea.html">FM・広告枠検索</a></li>
				<li><a class="menu-item" href="ad_list.html">担当広告一覧</a></li>
				<li><a class="menu-item" href="media.html">媒体資料</a></li>
				<li><a class="menu-item" href="case.html">事例紹介</a></li>
				<li><a class="menu-item" href="response.html">レスポンス入力</a></li>
				<li><a class="menu-item" href="photo.html">写真管理</a></li>
				<li class="cate">
					<a class="menu-item" href="#">マスタ管理</a>
					<ul>
						<li><a class="menu-item" href="http://localhost/zf2/public/application/master/departments/index">部門管理</a></li>
						<li><a class="menu-item" href="http://localhost/zf2/public/application/master/branchs/index">営業所管理</a></li>
						<li><a class="menu-item" href="http://localhost/zf2/public/application/master/areas/index">エリア管理</a></li>
						<li><a class="menu-item" href="kibo01.html">企業規模管理</a></li>
						<li><a class="menu-item" href="tgyosyu01.html">得意先業種管理</a></li>
						<li><a class="menu-item" href="baitai01.html">媒体管理</a></li>
						<li><a class="menu-item" href="sukesute01.html">スケジュールステータス管理</a></li>
						<li><a class="menu-item" href="koukokusize01.html">広告サイズ管理</a></li>
						<li><a class="menu-item" href="nyuryoku01.html">入力フォーマット管理</a></li>
						<li><a class="menu-item" href="tokui01.html">得意先管理</a></li>
						<li><a class="menu-item" href="ngword01.html">NGワード管理</a></li>
						<li><a class="menu-item" href="koukokucpn01.html">広告クーポン注意書き管理</a></li>
					</ul>
				</li>
				<li><a class="menu-item" href="tmpl01.html">テンプレート登録（クリエ)</a></li>
				<li><a class="menu-item" href="plan01.html">企画管理(管理本部？クリエ？)</a></li>

				
				<li class="cate">
					<a class="menu-item" href="#">社員系</a>
					<ul>
						<li><a class="menu-item" href="staff01.html">社員管理(管理本部)</a></li>
						<li><a class="menu-item" href="yu-za-01.html">ユーザー権限管理</a></li>
						<li><a class="menu-item" href="tanmatu.html">管理端末管理</a></li>
						<li><a class="menu-item" href="pin01.html">PINコード発行(管理本部)</a></li>
					</ul>

				<li class="cate">
					<a class="menu-item" href="#">仕入先・得意先</a>
					<ul>
						<li><a class="menu-item" href="shiire01.html">仕入先管理</a></li>
						<li><a class="menu-item" href="client_sea.html">得意先検索</a></li>
					</ul>
				</li>
				<li><a class="menu-item" href="vc01.html">VC管理</a></li>

				
			</ul>
		</nav>
	</div>
	<!-- //slidemenu end -->


	<!-- wrapper start -->
	<div id="wrapper">
	<?php echo $this->content; ?>
	</div>
	<!-- //wrapper end -->
</div>
<!-- //main end -->

</body>
</html>
