

<div id="system_mes">
	<p>クライアントB　サルぼぼ　おせち特集は自動キャンセルされました。　<button>確認</button></p>
</div>

<article>
	<h1>作業中の広告一覧</h1>
	<table class="tbl_type01">
		<tr>
			<th class="w25">クライアント名</th>
			<th class="w15">FM名</th>
			<th class="w10">掲載号</th>
			<th class="w20">広告企画名</th>
			<th class="w15">校了日</th>
			<th class="w15">ステータス</th>
		</tr>
		<tr>
			<td>クライアントA</td>
			<td>さるポポ</td>
			<td>2015/01</td>
			<td>バレンタイン特集</td>
			<td>2015/01/20</td>
			<td>未入稿</td>
		</tr>
		<tr>
			<td>クライアントA</td>
			<td>さるポポ</td>
			<td>2015/01</td>
			<td>春のお出かけ特集</td>
			<td>2015/01/20</td>
			<td>未校了</td>
		</tr>
		<tr>
			<td>クライアントB</td>
			<td>さるポポ</td>
			<td>2015/01</td>
			<td>バレンタイン特集</td>
			<td>2015/01/20</td>
			<td>サイン未受領</td>
		</tr>
		<tr class="bg_red1">
			<td>クライアントC</td>
			<td>かにさんクラブ</td>
			<td>2015/01</td>
			<td>お正月特集</td>
			<td>2015/01/10</td>
			<td>承認申込</td>
		</tr>
		<tr class="bg_red1">
			<td>クライアントC</td>
			<td>かにさんクラブ</td>
			<td>2014/11</td>
			<td>お正月特集</td>
			<td>2015/01/10</td>
			<td>校了済/レスポンス未入力</td>
		</tr>
	</table>
</article>

<article>
	<h1>枠押え済み一覧</h1>
	<table class="tbl_type01 w100">
		<tr>
			<th class="w25">クライアント名</th>
			<th class="w15">FM名</th>
			<th class="w10">掲載号</th>
			<th class="w20">広告企画名</th>
			<th class="w15">校了日</th>
			<th class="w15">ステータス</th>
		</tr>
		<tr>
			<td>クライアントA</td>
			<td>さるポポ</td>
			<td>2015/01</td>
			<td>バレンタイン特集</td>
			<td>2015/01/20</td>
			<td>未入稿</td>
		</tr>
	</table>
</article>

<article>
	<h1>未振り分け一覧</h1>
	<table class="tbl_type03 w100">
		<tr>
			<th class="w25">クライアント名</th>
			<th class="w15">FM名</th>
			<th class="w10">掲載号</th>
			<th class="w15">校了日</th>
			<th class="w15">ステータス</th>
		</tr>
		<tr>
			<td><a href="application_sea.html">クライアントB</a></td>
			<td><a href="application_sea.html">さるポポ</a></td>
			<td><a href="application_sea.html">2015/01</a></td>
			<td><a href="application_sea.html">2015/01/20</a></td>
			<td><a href="application_sea.html">未入稿</a></td>
		</tr>
	</table>
</article>

<article>
	<h1>承認依頼一覧</h1>
	<table class="tbl_type03 w100">
		<tr>
			<th class="w25">クライアント名</th>
			<th class="w15">FM名</th>
			<th class="w10">掲載号</th>
			<th class="w15">校了日</th>
			<th class="w15">ステータス</th>
		</tr>
		<tr>
			<td><a href="irai.html">クライアントC</a></td>
			<td><a href="irai.html">ぎふと</a></td>
			<td><a href="irai.html">2015/01</a></td>
			<td><a href="irai.html">2015/01/20</a></td>
			<td><a href="irai.html">承認依頼</a></td>
		</tr>
	</table>
</article>



<article>
	<h1>滞留案件クライアント</h1>
	<table class="tbl_type01 w40">
		<tr>
			<th>クライアント名</th>
		</tr>
		<tr>
			<td>クライアントZ</td>
		</tr>
		<tr>
			<td>クライアントX</td>
		</tr>
	</table>
</article>